"""add_ad_configurations_table

Revision ID: 20a559b7264f
Revises: 2adcbe1f5dfb
Create Date: 2025-05-31 15:47:40.139988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20a559b7264f'
down_revision = '2adcbe1f5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('bind_dn', sa.String(length=255), nullable=True),
    sa.Column('encrypted_bind_password', sa.LargeBinary(), nullable=True),
    sa.Column('user_search_base', sa.String(length=255), nullable=False),
    sa.Column('user_search_filter', sa.String(length=1024), nullable=False),
    sa.Column('group_search_base', sa.String(length=255), nullable=True),
    sa.Column('group_search_filter', sa.String(length=1024), nullable=True),
    sa.Column('attribute_mapping_username', sa.String(length=255), nullable=False),
    sa.Column('attribute_mapping_email', sa.String(length=255), nullable=False),
    sa.Column('attribute_mapping_display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_configurations')),
    schema='extensions'
    )
    with op.batch_alter_table('ad_configurations', schema='extensions') as batch_op:
        batch_op.create_index(batch_op.f('ix_extensions_ad_configurations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_configurations', schema='extensions') as batch_op:
        batch_op.drop_index(batch_op.f('ix_extensions_ad_configurations_tenant_id'))

    op.drop_table('ad_configurations', schema='extensions')
    # ### end Alembic commands ###
