"""add_ad_user_dn_to_accounts_table

Revision ID: 22b548aeb943
Revises: 20a559b7264f
Create Date: 2025-05-31 15:51:20.243031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b548aeb943'
down_revision = '20a559b7264f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_user_dn', sa.String(length=255), nullable=True, comment='Active Directory User Distinguished Name'))
        batch_op.create_index(batch_op.f('ix_accounts_ad_user_dn'), ['ad_user_dn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_ad_user_dn'))
        batch_op.drop_column('ad_user_dn')

    # ### end Alembic commands ###
